import React, { useState, useEffect } from 'react';
import { View, StyleSheet, ScrollView, TouchableOpacity, Dimensions, Share, Alert } from 'react-native';
import { Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import * as Speech from 'expo-speech';
import Screen from '../components/Screen';
import AppText from '../components/AppText';
import { colors } from '../theme/colors';

const { width } = Dimensions.get('window');

export default function TipDetailScreen({ route, navigation }) {
    const { tip } = route.params || {};
    const [isSpeaking, setIsSpeaking] = useState(false);

    // Stop speaking when user exits the screen
    useEffect(() => {
        return () => {
            Speech.stop();
        };
    }, []);

    const toggleSpeech = async () => {
        try {
            const isDictating = await Speech.isSpeakingAsync();
            if (isDictating || isSpeaking) {
                Speech.stop();
                setIsSpeaking(false);
            } else {
                setIsSpeaking(true);
                // Strip invalid symbols that crash parsing
                let fullText = `${tip.title}. ${tip.content}`.replace(/[^a-zA-Z0-9 .,!?]/g, '');

                // CRITICAL FIX: Android TTS silently fails if text is too long.
                // We must break it into sentences and enqueue them sequentially!
                const sentences = fullText.split('.').filter(s => s.trim().length > 0);

                sentences.forEach((sentence, index) => {
                    Speech.speak(sentence.trim(), {
                        language: 'en-US',
                        rate: 0.9,
                        onDone: () => {
                            if (index === sentences.length - 1) setIsSpeaking(false);
                        },
                        onStopped: () => {
                            if (index === sentences.length - 1) setIsSpeaking(false);
                        },
                        onError: (e) => {
                            console.error("TTS Error:", e);
                            if (index === sentences.length - 1) setIsSpeaking(false);
                        }
                    });
                });
            }
        } catch (err) {
            console.error("Speech init err", err);
            setIsSpeaking(false);
        }
    };

    const handleShare = async () => {
        try {
            const message = `🌱 ArecaCare AI Advisory\n\n*${tip.title}*\n${tip.content}\n\nGenerated by ArecaCare AI`;
            await Share.share({
                message: message,
                title: tip.title,
            });
        } catch (error) {
            console.error("Share failed", error);
            Alert.alert("Share Failed", "Could not share the advisory link.");
        }
    };

    if (!tip) {
        return (
            <Screen style={styles.screen}>
                <AppText>Error loading tip.</AppText>
            </Screen>
        );
    }

    return (
        <Screen style={styles.screen} noPadding>
            <ScrollView style={styles.scrollRoot} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>

                {/* Visual Header Graphic */}
                <LinearGradient colors={['#A7F3D0', '#34D399']} style={styles.heroBlock}>
                    <SafeAreaHeader
                        navigation={navigation}
                        isSpeaking={isSpeaking}
                        onSpeech={toggleSpeech}
                        onShare={handleShare}
                    />
                    <View style={styles.heroIconWrapper}>
                        <MaterialCommunityIcons name={tip.icon} size={80} color="#065F46" />
                    </View>
                </LinearGradient>

                {/* Content Body */}
                <View style={styles.articleBody}>
                    <View style={styles.metaRow}>
                        <View style={styles.pill}>
                            <AppText variant="caption" color="primary" style={styles.pillText}>
                                {tip.category}
                            </AppText>
                        </View>
                        <View style={styles.timeWrapper}>
                            <Feather name="clock" size={14} color={colors.textMedium} />
                            <AppText variant="caption" style={styles.timeText}>
                                {tip.readTime}
                            </AppText>
                        </View>
                    </View>

                    <AppText variant="heading1" style={styles.title}>
                        {tip.title}
                    </AppText>

                    <View style={styles.divider} />

                    {tip.content.split('\n').map((paragraph, index) => (
                        paragraph.trim() ? (
                            <AppText key={index} variant="bodyMedium" style={styles.paragraph}>
                                {paragraph.trim()}
                            </AppText>
                        ) : null
                    ))}
                </View>
            </ScrollView>
        </Screen>
    );
}

// Sub-component to float over the hero graphic
const SafeAreaHeader = ({ navigation, isSpeaking, onSpeech, onShare }) => (
    <View style={styles.floatHeader}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.actionBtn}>
            <Feather name="arrow-left" size={24} color="#064E3B" />
        </TouchableOpacity>

        <View style={styles.rightActions}>
            <TouchableOpacity onPress={onSpeech} style={[styles.actionBtn, isSpeaking && styles.activeBtn]}>
                <Feather name={isSpeaking ? "volume-x" : "volume-2"} size={22} color={isSpeaking ? "white" : "#064E3B"} />
            </TouchableOpacity>

            <TouchableOpacity onPress={onShare} style={styles.actionBtn}>
                <Feather name="share-2" size={22} color="#064E3B" />
            </TouchableOpacity>
        </View>
    </View>
);

const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: colors.background
    },
    scrollRoot: {
        flex: 1,
    },
    content: {
        paddingBottom: 60,
    },
    heroBlock: {
        width: '100%',
        height: 280,
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 40,
    },
    floatHeader: {
        position: 'absolute',
        top: 20,
        left: 20,
        right: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        zIndex: 10,
    },
    rightActions: {
        flexDirection: 'row',
        gap: 12, // Requires RN 0.71+, safe for Expo 48+
    },
    actionBtn: {
        width: 48,
        height: 48,
        backgroundColor: 'rgba(255,255,255,0.7)',
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 8,
    },
    activeBtn: {
        backgroundColor: colors.primary,
    },
    heroIconWrapper: {
        width: 130,
        height: 130,
        backgroundColor: 'rgba(255,255,255,0.4)',
        borderRadius: 65,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: 'rgba(0,0,0,0.1)',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 1,
        shadowRadius: 20,
    },
    articleBody: {
        paddingHorizontal: 24,
        paddingTop: 30,
    },
    metaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    pill: {
        backgroundColor: '#ECFDF5',
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 20,
    },
    pillText: {
        fontWeight: '800',
        letterSpacing: 0.5,
    },
    timeWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    timeText: {
        marginLeft: 6,
        color: colors.textMedium,
        fontWeight: '600',
    },
    title: {
        fontSize: 32,
        lineHeight: 40,
        fontWeight: '800',
        color: colors.text,
        marginBottom: 24,
    },
    divider: {
        height: 1,
        backgroundColor: 'rgba(0,0,0,0.05)',
        marginBottom: 24,
    },
    paragraph: {
        fontSize: 17,
        lineHeight: 28,
        marginBottom: 20,
        color: '#4B5563', // Rich gray for premium legibility
    }
});
